x = "Hello World"
x = 20
x = 20.5
x = ["apple", "banana","cherry"]
x = ("apple", "banana","cherry")
x = {"name": "pipusana", "age": 26}
x = {"apple", "banana","cherry"}
x = frozenset({"apple", "banana","cherry"})
x = True
x = b"hello"
